version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"